
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AR
 */
public class class_select extends javax.swing.JFrame {

    /**
     * Creates new form class_select
     */ public class_select() {
        initComponents();
     }
    String un;
    public class_select(String a) {
        
        
        
        initComponents();
        un=a;
        
          jTable1.setOpaque(false);
    ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    
        
        Connection con = null;
        PreparedStatement st = null;
        ResultSet res = null;

        String cdd = "Select USER_CLASS.CLASS from BURHAN.USER_CLASS WHERE USER_CLASS.USER_NAME='"+un+"'";
        String cl="";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int yy=0;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/login", "Burhan", "burhan14");
            st = con.prepareStatement(cdd);
            res = st.executeQuery();

            while (res.next()) {

                cl = res.getString("CLASS");
                 model.addRow( new Object[]{cl});
yy++;

            }
            if(yy==0)
            {
                JOptionPane.showMessageDialog(new JFrame(), "NO result found", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(new JFrame(), "wrong", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 570));
        setPreferredSize(new java.awt.Dimension(400, 570));
        getContentPane().setLayout(null);

        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select your Class....");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 70, 300, 20);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Join Class");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(130, 0, 120, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Classes"
            }
        ));
        jTable1.setAlignmentX(5.0F);
        jTable1.setAlignmentY(5.0F);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setOpaque(false);
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 51, 204));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 370, 350);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 510);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 30, 390, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        int column = source.columnAtPoint( evt.getPoint() );
        String s1=source.getModel().getValueAt(row, 0)+"";
        String c="update BURHAN.CLASS SET ACTIVE=1 WHERE CLASS.NAME = '"+s1+"'";
        String c2="update BURHAN.CLASS SET ACTIVE=0 WHERE CLASS.ACTIVE = "+1+"";
        
        try {
            Connection con = null;
            PreparedStatement st = null;
            ResultSet res = null;

            con = DriverManager.getConnection("jdbc:derby://localhost:1527/login", "Burhan", "burhan14");
                 st = con.prepareStatement(c2);
                   st.executeUpdate();
          st = con.prepareStatement(c);
                   st.executeUpdate();
          
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Wrong Username or Password", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

        JOptionPane.showMessageDialog(new JFrame(), "Class selected seccesfully", "ERROR", JOptionPane.ERROR_MESSAGE);
        this.setVisible(false);
        page_2nd aq=new page_2nd();
        aq.setVisible(true);
        // JOptionPane.showMessageDialog(null, s);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(class_select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(class_select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(class_select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(class_select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new class_select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
