
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AR
 */
public class registerUni extends javax.swing.JFrame {

    /**
     * Creates new form registerUni
     */
    public registerUni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 570));
        setPreferredSize(new java.awt.Dimension(400, 570));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 390, 30);

        jPanel4.setLayout(null);

        jButton1.setText("Register!");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(120, 250, 160, 40);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("University Name :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 150, 120, 30);

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 51, 255), java.awt.Color.gray, java.awt.Color.gray, new java.awt.Color(51, 51, 255)));
        jPanel4.add(jTextField1);
        jTextField1.setBounds(140, 150, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piazalogo.png"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(80, 20, 250, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 390, 510);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 30, 390, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
       String str=jTextField1.getText(); 
                 
        Connection con = null;
        PreparedStatement st = null;
        ResultSet res = null;
        String c = "Select NAME from BURHAN.UNIVERSITIES";
        boolean check=false;
         String un="";
      
              try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/login", "Burhan", "burhan14");
            st = con.prepareStatement(c);
            res = st.executeQuery();
           
            while (res.next()) 
            {
                un = res.getString("NAME");
                if(str.equalsIgnoreCase(un))
                {
                    check=true;
                    break;
                }
                
            }
             
            if(check==true)
            {
             JOptionPane.showMessageDialog(new JFrame(), "Sorry, But The university id already registered! ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
               c="INSERT INTO UNIVERSITIES(NAME) VALUES(?)" ;
                 st = con.prepareStatement(c);
                st.setString(1,str);
                 st.executeUpdate();
                 JOptionPane.showMessageDialog(new JFrame(), "The university is registered! ", "ERROR", JOptionPane.ERROR_MESSAGE);
                   this.setVisible(false);
                   Sign_uniSelect aa=new Sign_uniSelect(2);
                   aa.setVisible(true);
            
            }
            
                  }
              
              catch (SQLException e) 
              { 
                    JOptionPane.showMessageDialog(new JFrame(), "Wrong Username or Password", "ERROR", JOptionPane.ERROR_MESSAGE);
              }

              
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
